databricks:
  outputs:
    dev:
      catalog: null
      host: 2069279851173120.0.gcp.databricks.com
      http_path: sql/protocolv1/o/2069279851173120/1215-114022-wnkoe1x4
      schema: default
      threads: 48
      token: dapi0b5a1b433e5ed2bf22de7b83ed678968
      type: databricks
    prod:
      catalog: null
      host: 2069279851173120.0.gcp.databricks.com
      http_path: sql/protocolv1/o/2069279851173120/1215-114022-wnkoe1x4
      schema: default
      threads: 48
      token: dapi0b5a1b433e5ed2bf22de7b83ed678968
      type: databricks
  target: dev
postgres_test:
  outputs:
    dev:
      type: postgres
      host: 52.17.135.55
      user: test_user
      password: 85dLRZHnkZHZk6Yoy0Ww0NW3ZgnW0u2J9SSkjVCbQ0
      port: 36603
      dbname: test_db
      schema: public
      threads: 4
  target: dev